version: '3.3'

services:

  curator:
    image: dec_curator:latest
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      CRON: 0 0 * * *
      CONFIG_FILE: /usr/share/curator/config/curator.yml
      COMMAND: /usr/share/curator/config/delete_log_files_curator.yml
      UNIT_COUNT: 8
    configs:
      - source: curator_config
        target: /usr/share/curator/config/curator.yml
      - source: curator_delete_log_files
        target: /usr/share/curator/config/delete_log_files_curator.yml
    deploy:
      replicas: 1
    networks:
      - elk

configs:
  curator_config:
    file: ./extensions/curator/config/curator.yml
  curator_delete_log_files:
    file: ./extensions/curator/config/delete_log_files_curator.yml